# backend-secret.yaml
# Sensitive database credentials for the backend

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_USER: bW9uaXRvcl91c2Vy
  DB_PASSWORD: bW9uaXRvcl9wYXNz